### ISSUE TITLE
Using web-server outside the localhost

### ISSUE THREAD

**Issue by Svyatk0** [gpac/node-gpac-dash#6]
hi guys. 

I am a bit new to the whole node thing, and I cant seem to understand what is missing to enable this server to work outside the localhost. 

if I do the *_curl http://127.0.0.1:8000/output/dashcast.mpd *_ locally, it works fine. 
trying the same from another machine on a local network, I get "Connection refused". on the playback machine I am obviously calling the IP of the node web server, not locahost. 

any pointers would be appreciated. 

Thanks

**Comment by Svyatk0** [comment]
figured 
replace **http.createServer(onRequest).listen(port, ipaddr);**
 line with **http.createServer(onRequest).listen(parseInt(port, 10));**

svyatko

**Comment by cconcolato** [comment]
Thank you for the report. Your issue could have been solved also by providing the IP address of your server using "-ip" when starting the server, instead of relying on the default value of 127.0.0.1. However, I think setting the server to accept connections on all IP addresses as you did is good. We'll fix that in the code.
